services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__PostgreDevelopment=${ConnectionStrings__PostgreDevelopment}
    env_file:
      - .env
