@startuml
    ' Presentation Layer
    package "Presentation" {
        class ToDosPage {
            -toDosWidget: ToDosWidget
            +render()
        }

        class ToDosWidget {
            -grid: Grid
            +render(): UIElement
        }

        class ToDoCard {
            -viewModel: ToDoViewModel
            +render(): UIElement
        }

        class Grid {
            -items: ToDoCard[]
            +render(): UIElement
        }
    }

    ' Domain Layer
    package "Domain" {
        class ToDosViewModel {
            -todosService: ToDosService
            +init(): void
        }

        class ToDoViewModel {
            -todosService: ToDosService
            +init(): void
        }

        class ViewModel {
            +data: object
            +setData(data: object): void
            +subscribe(callback: Function): void
            +unsubscribe(callback: Function): void
        }

        class ToDoImpl {
            -owner: ToDosOwner
        }

        class ToDo {
            +string id
            +string title
            +string description
            +Date completionDatePlanned
            +Date completionDateActual            
        }

        class ToDosOwner {
            +getToDoById(id: string): ToDo
            +getAllToDos(): ToDo[]
            +saveToDo(toDo: ToDo)
            +removeToDo(toDo: ToDo)
        }

        class ToDosOwnerBase {
            -service: ToDosRepository
        }
        
        class ToDosService {
            -owner: ToDosOwner
            +getToDoById(id: string): ToDo
            +getAllToDos(): ToDo[]
            +saveToDo(toDo: ToDo): void
            +removeToDo(toDo: ToDo): void
        }
    }

    ' Data Layer
    package "Data" {
        class ToDosRepository {
            +addToDoAsync(data: AddToDoDto): Promise~ToDo~
            +updateToDoAsync(data: UpdateToDoDto): Promise~void~
            +getToDoByIdAsync(id: string): Promise~ToDo~
            +getAllToDosAsync(): Promise~ToDo[]~
            +removeToDoAsync(id: string): Promise~void~
        }
    }

    ' Зависимости между слоями
    ToDosPage --> ToDosWidget : uses
    ToDosWidget --> ToDoCard : creates
    ToDosWidget --> Grid : uses
    ToDosWidget --> ToDosViewModel : uses
    ToDoCard --> ToDoViewModel : uses
    ToDosViewModel --> ToDosService : depends on
    ToDoViewModel --> ToDosService : depends on
    ToDosService --> ToDosOwner : depends on
    ToDosOwnerBase --> ToDosRepository : depends on
    ToDo --> ToDosOwner : for saving changes
    ToDoImpl --> ToDosOwner : depends on
    ToDosOwnerBase <|-- ToDosOwner
    ToDosViewModel <|-- ViewModel
    ToDoViewModel <|-- ViewModel
    ToDosService <|-- ViewModel
@enduml
